hokimicms/tools/server/src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve', { 'insecure': True }),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
) + i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

hokimicms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from django.contrib.auth import views as auth_views
from test.views import index, health

from machina.app import board

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += [url(r'^test$', index),
				url(r'^test/health$', health),]
				
urlpatterns += i18n_patterns(
#     url(r'^accounts/login/$', auth_views.login),
    url(r'^', include('torneos.urls', namespace="torneos", app_name="torneos"), name="torneos"),
    # url(r'^', include('competition.urls')),  # NOQA
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
) + [url(r'^forum/', include(board.urls)),]

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

torneos/urls.py
from django.conf.urls import url

from .views import torneo_views
from .views.registration_views import RegistrationView
from .views.score_views import ScoreView
from .views import profile_view

app_name = "torneos"
urlpatterns = [
	url(r'^profile/$',  torneo_views.update_profile, name="profile"),
    url(r'^password/$', profile_view.change_password, name='change_password'),
	url(r'^signup/$', profile_view.signup, name='signup'),

    url(r'^account_activation_sent/$', profile_view.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        profile_view.activate, name='activate'),
	
	url(r'^competiciones/$', torneo_views.index, name='index'),
	url(r'^competiciones/(?P<torneo_id>[0-9]+)/$', torneo_views.detail, name='torneos_detail'),
	url(r'^competiciones/(?P<torneo_id>[0-9]+)/(?P<slug>[-\w]+)/$',  
		torneo_views.TorneoDetailView.as_view(), 
		name="torneos_detail_slug"),

    url(r'^competiciones/(?P<torneo_id>[0-9]+)/(?P<slug>[\w-]+)/register/$',
        RegistrationView.as_view(),
        name='register_for'),

    url(r'^competiciones/(?P<torneo_id>[0-9]+)/(?P<slug>[\w-]+)/submission/$',
        ScoreView.as_view(),
        name='submission_for'),
]

torneos/forms/profile_forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext, ugettext_lazy as _

from ..models.profile_model import  Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        first_name = forms.CharField(required=True)
        last_name = forms.CharField(required=True)
        email = forms.EmailField(label='Your email', required=True)
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        bio = forms.CharField(widget=forms.Textarea)
        fields = ('bio',)

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

torneos/forms/score_forms.py
from django import forms
from django.contrib.auth.models import User
from ..models.score_model import Score
from ..models.torneo_model import Torneo


class ScoreForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(),
            widget=forms.HiddenInput())
    competition = forms.ModelChoiceField(queryset=Torneo.objects.all(),
            widget=forms.HiddenInput())

    score = forms.CharField(widget = forms.HiddenInput(), required = False)
    error = forms.CharField(widget = forms.HiddenInput(), required = False)

    class Meta:
        model = Score
        fields = ('description', 'document')

torneos/views/mixins.py
from django import forms
from django.http import Http404
from django.contrib import messages
from django.views.generic import View
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from ..models.torneo_model import Torneo

import logging

logger = logging.getLogger(__name__)


class TorneoViewMixin(View):
    """A mixin class for adding a competition accessor to the class
    (i.e. self.get_competition()) and adding a competition object to
    the template context, if necessary."""
    def get_torneo(self):
        """Returns the competition for the given view.  This requires
        that self.kwargs be set"""
        if not hasattr(self, "_comp"):
            try:
                t_id = self.kwargs['torneo_id']
                self._comp = get_object_or_404(Torneo, t_id=t_id)
            except KeyError:
                msg = "Couldn't find comp_slug in kwargs"
                logger.error(msg)
                raise Http404(msg)

        return self._comp

    def dispatch(self, request, *args, **kwargs):
        """Overrides dispatch function to load competition
        information. Raises a Http404 if the competition with slug
        kwargs['comp_slug'] doesn't exist"""
        self.kwargs = kwargs
        self.get_torneo()  # Throws Http404 if not found
        parent = super(TorneoViewMixin, self)
        return parent.dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        """Overrides get_context_data to add 'competition' to the
        template context before rendering"""
        c = self.get_torneo()
        user = self.request.user

        try:
            team = c.team_set.get(members=user)
        except ObjectDoesNotExist:
            team = None

        context = {
            'torneo': c,
            'user_registered': c.is_user_registered(user),
            'user_team': team,
        }
        # Update the context with the parent's context
        parent = super(TorneoViewMixin, self)
        context.update(parent.get_context_data(*args, **kwargs))
        return context


class LoggedInMixin(View):
    """A mixin class for checking that a user is logged in"""
    redirect_field_name = "next"
    login_url = None

    def login_required(self, dispatch_function):
        """Wraps a function with login_required. Intended to be used
        to wrap a View's dispatch function"""
        return login_required(dispatch_function,
                              redirect_field_name=self.redirect_field_name,
                              login_url=self.login_url)

    def dispatch(self, request, *args, **kwargs):
        """Overrides dispatch by wrapping dispatch with
        login_required"""
        parent = super(LoggedInMixin, self)
        wrapped_function = self.login_required(parent.dispatch)
        return wrapped_function(request, *args, **kwargs)


class UserRegisteredMixin(TorneoViewMixin, LoggedInMixin):
    """A mixin class for checking that a user is registered for a
    competition"""

    def dispatch(self, request, *args, **kwargs):
        """Overrides dispatch and does the following
           - Checks that a user is authenticated
           - Loads the competition with slug kwargs['comp_slug']
               - Raises a Http404 otherwise
           - Checks that a user is reigstered for the loaded competition
               - Raises a Http404 if they aren't registered"""
        self.kwargs = kwargs    # Needed for get_competition()

        # Causes a 404 if comp_slug kwarg is bad or if the user
        # isn't registered for the corresponding competition
        self.registered_or_404(request)

        # Checks that a user is logged in before returning
        parent = super(UserRegisteredMixin, self)
        wrapped_function = self.login_required(parent.dispatch)
        return wrapped_function(request, *args, **kwargs)

    def registered_or_404(self, request):
        """Checks that the user is registered for the competition
        whose competition slug is kwargs['comp_slug']. If the user is
        not registered, raises Http404"""
        # Causes a 404 if the comp_slug kwarg is bad
        competition = self.get_torneo()
        if not competition.is_user_registered(request.user):
            raise Http404("User isn't registered")


# class ConfirmationMixin(FormView):
#     question = None
#     check_box_label = "OK"

#     def get_question(self):
#         if self.question is None:
#             raise Exception("question not set for ConfirmationMixin")
#         return self.question

#     def get_check_box_label(self):
#         return self.check_box_label

#     def get_context_data(self, **kwargs):
#         kwargs['question'] = self.get_question()
#         return super(FormView, self).get_context_data(**kwargs)

#     def get_form_class(self):

#         class ConfirmationForm(forms.Form):
#             confirmed = forms.BooleanField(required=False,
#                                            label=self.get_check_box_label())

#         return ConfirmationForm

#     def form_valid(self, form):
#         if form.cleaned_data['confirmed']:
#             return self.agreed()
#         return self.disagreed()

#     def agreed(self):
#         """If the user agreed, redirect them to the success url"""
#         return redirect(self.get_success_url())

#     def disagreed(self):
#         """If the user disagreed, redirect them to the success url"""
#         return redirect(self.get_success_url())


class CheckAllowedMixin(View):
    """This mixin throws a 404 if certain conditions are not met.

    At the beginning of the request, this mixin calls
    ``check_if_allowed()`` to see if the user is allowed to view the
    page. If not, it calls ``get_error_message()``, sets an error
    message with level ``self.message_level``, and calls
    ``was_not_allowed`` to determine how to handle the error. The
    default is to throw a 404.

    If the user is allowed to view the page, everything proceeds as
    usual.
    """
    error_message = "You cannot do that"
    message_level = messages.INFO

    def dispatch(self, request, *args, **kwargs):
        is_allowed = self.check_if_allowed(request)
        if not isinstance(is_allowed, bool):
            msg = "check_if_allowed method returned something "
            msg += "other than True or False"
            logger.warning(msg)
        if not is_allowed:
            msg = self.get_error_message(request)
            messages.add_message(request, self.message_level, msg)
            return self.was_not_allowed(request)

        parent = super(CheckAllowedMixin, self)
        return parent.dispatch(request, *args, **kwargs)

    def check_if_allowed(self, request):
        """Called to see if a user is allowed to view this page. It
        should return True if they're allowed, and False otherwise.
        """
        raise Exception("check_if_allowed() is not overridden.")

    def get_error_message(self, request):
        """Called to get the user's error message. If not overridden,
        we'll just use ``self.error_message``
        """
        return self.error_message

    def was_not_allowed(self, request):
        """Called if check_if_allowed returned False. If not
        overridden, we'll just throw a 404"""
        raise Http404(self.get_error_message(request))


# class RequireRunningMixin(CheckAllowedMixin):
#     """This mixin throws a 404 if the current competition is not running
#     """
#     error_message = "You cannot do that because the competition is not running"

#     def check_if_allowed(self, request):
#         """Called to see if a user is allowed to view this page.
#         """
#         # If the competition is running, they're allowed to view it
#         return self.get_competition().is_running

#     def get_competition(self):
#         """Gets the instance of the competition to check.  

#         You could just inherit from CompetitionViewMixin, which
#         provides get_competition, just make sure that it's listed
#         before RequireRunningMixin when inheriting in the view
#         """
#         raise Exception("get_competition() not implemented")


# class RequireNotRunningMixin(CheckAllowedMixin):
#     """This mixin throws a 404 if the current competition is running
#     """
#     error_message = "You cannot do that because the competition is running"

#     def check_if_allowed(self, request):
#         """Called to see if a user is allowed to view this page.
#         """
#         # If the competition is running, they're NOT allowed to view it
#         return not self.get_competition().is_running

#     def get_competition(self):
#         """Gets the instance of the competition to check.  

#         You could just inherit from CompetitionViewMixin, which
#         provides get_competition, just make sure that it's listed
#         before RequireRunningMixin when inheriting in the view
#         """
#         raise Exception("get_competition() not implemented")


class RequireOpenMixin(CheckAllowedMixin):
    """This mixin throws a 404 if the current competition is not open
    """
    error_message = "You cannot do that because the competition is not open"

    def check_if_allowed(self, request):
        """Called to see if a user is allowed to view this page.
        """
        # If the competition is open, they're allowed to view it
        # return self.get_torneo().is_open
        return True

    def get_torneo(self):
        """Gets the instance of the competition to check.  

        You could just inherit from CompetitionViewMixin, which
        provides get_competition, just make sure that it's listed
        before RequireRunningMixin when inheriting in the view
        """
        raise Exception("get_competition() not implemented")

torneos/views/profile_view.py
from django.shortcuts import render, redirect

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string

from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from ..tokens import account_activation_token
from ..forms.profile_forms import SignUpForm



# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your Hokimi account'
            message = render_to_string('profiles/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('torneos:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'profiles/signup.html', {'form': form})    

def account_activation_sent(request):
    return render(request, 'profiles/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('pages-root')
    else:
        return render(request, 'account_activation_invalid.html')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('torneos:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'profiles/change_password.html', {
        'form': form
    })

torneos/templates/torneos/breadcrumb.html
{% block breadcrumb %}
<li><a href="{% url 'torneos:index' %}">Competiciones</a>
<li>{{torneo.title}}</li>
{% endblock %}

torneos/templates/torneos/detail.html
{% extends "torneo.html" %}
{% load i18n staticfiles cms_tags menu_tags sekizai_tags %}

{% block title %}{{object.title}}{% endblock title %}


{% block breadcrumb %}
<!-- start: breadcrumb 
{# INFO: breadcrumb concept: http://getbootstrap.com/components/#breadcrumbs #}
<nav class="navbar navbar-breadcrumb" role="navigation">
    <h3 class="sr-only">{% trans "You are here" %}</h3>
    <div class="container">
        <ol class="breadcrumb">
{% block extend_breadcrumb %}
{% show_breadcrumb 0 "torneos/breadcrumb.html" 0 %}
{% endblock extend_breadcrumb %}
        </ol>
    </div>
</nav>
<!-- end: breadcrumb -->
{% endblock breadcrumb %}



{% block content %}
<div class="container">
	<div class="spacer spacer-xs"></div>
	<div class="row">
		<div class="col-md-4">
			<div class="spacer spacer-xs"></div>
			<img src="{{ MEDIA_URL }}{{ object.image.name }}" alt="" class="img-responsive"></img>
		</div>
		<div class="col-md-20">
			<h2>{{object.title}}</h2>
			<h4>{{object.short_description}}</h4>
			<p>{{object.first_prize}} - 152 participantes - Un mes para finalizar</p>
		</div>
	</div>
	<div class="row">
		<div class="col-md-16">
			<h4>Descripción</h4>
			{{object.long_description}}
			<hr>
			<h4>Evaluación</h4>
			{{object.evaluation}}
			<hr>
			<h4>Datos</h4>
			<h5>Descripción de los datos</h5>
			{{object.data}}
			<h5>Descarga</h5>
			<ul>
				<li>sample_submission.csv.zip - 2.37 MB</li>
				<li>train_ver2.csv.zip - 241.36 MB</li>
				<li>test_ver2.csv.zip - 12.39</li>
			</ul>
		</div>
		<div class="col-md-8">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Premios</h3>
				</div>
				<div class="panel-body">
					{{object.prizes}}

					{% if not user_registered %}
					<div class="text-center">
				      	<a href="{% url 'torneos:register_for' torneo_id=object.t_id slug=object.slug %}" 
				      	class="btn btn-warning btn-lg cms-plugin cms-plugin-2292 fa fa-pencil-square-o" role="button"> ¡Participa!</a>
				    </div>
					{% endif %}				

				</div>
			</div>
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title">Clasificación</h3>
				</div>
				<div class="panel-body">
					<ol>
						<li>idle_speculation</li>
						<li>Tom Van de Wiele</li>
						<li>Jack (Japan)</li>
						<li>yoniko</li>
						<li>Jared Turkewitz and BreakfastPirate</li>
						<li>In Public Leaderboard We Trust</li>
						<li>Evgeny Patekha</li>
						<li>Alejo y Miro</li>
					</ol>
				</div>
			</div>
			<div class="panel panel-info">
				<div class="panel-heading">
					<h3 class="panel-title">Foros de discusión</h3>
				</div>
				<div class="panel-body">
					<div class="content-box__content-section discussion-teaser__items">
						<div class="teaser-list teaser-list--4-item-height">
							<div class="block-link block-link--bordered">
								<a class="block-link__anchor" href="/c/santander-product-recommendation/forums/t/26899/3rd-place-solution-with-code?forumMessageId=167502#post167502"></a>
								<div class="discussion-teaser__item">
									<div class="discussion-teaser__item-title">
										<a title="3rd place solution (with code)" style="" href="/c/santander-product-recommendation/forums/t/26899/3rd-place-solution-with-code?forumMessageId=167502#post167502">3rd place solution (with code)</a>
									</div>
									<div class="discussion-teaser__item-details">
										<span>12 replies</span> · <span title="Tue Mar 14 2017 11:19:38 GMT+0100 (CET)">3 days ago</span>
									</div>
								</div>
							</div>
							<div class="block-link block-link--bordered">
								<a class="block-link__anchor" href="/apryor6/santander-product-recommendation/detailed-cleaning-visualization-python/comments#166878"></a>
								<div class="discussion-teaser__item">
									<div class="discussion-teaser__item-title">
										<a title="Detailed Cleaning/Visualization (Python)" style="" href="/apryor6/santander-product-recommendation/detailed-cleaning-visualization-python/comments#166878">Detailed Cleaning/Visualization (Python)</a>
									</div>
									<div class="discussion-teaser__item-details">
										<span>66 replies</span> · <span title="Sat Mar 11 2017 19:28:07 GMT+0100 (CET)">6 days ago</span>
									</div>
								</div>
							</div>
							<div class="block-link block-link--bordered">
								<a class="block-link__anchor" href="/c/santander-product-recommendation/forums/t/24790/welcome?forumMessageId=164782#post164782"></a>
								<div class="discussion-teaser__item">
									<div class="discussion-teaser__item-title">
										<a title="Welcome! " style="" href="/c/santander-product-recommendation/forums/t/24790/welcome?forumMessageId=164782#post164782">Welcome!</a>
									</div>
									<div class="discussion-teaser__item-details">
										<span>29 replies</span> · <span title="Thu Mar 02 2017 12:07:17 GMT+0100 (CET)">15 days ago</span>
									</div>
								</div>
							</div>
							<div class="block-link block-link--bordered">
								<a class="block-link__anchor" href="/rahulgopal/santander-product-recommendation/recommender-system/comments#160703"></a>
								<div class="discussion-teaser__item">
									<div class="discussion-teaser__item-title">
										<a title="Recommender system" style="" href="/rahulgopal/santander-product-recommendation/recommender-system/comments#160703">Recommender system</a>
									</div>
									<div class="discussion-teaser__item-details">
										<span>0 replies</span> · <span title="Thu Feb 09 2017 06:48:33 GMT+0100 (CET)">a month ago</span>
									</div>
								</div>
							</div>
							<div class="block-link block-link--bordered">
								<a class="block-link__anchor" href="/k0walski/santander-product-recommendation/santander-prodct-recommendation/comments#159154"></a>
								<div class="discussion-teaser__item">
									<div class="discussion-teaser__item-title">
										<a title="Santander prodct recommendation" style="" href="/k0walski/santander-product-recommendation/santander-prodct-recommendation/comments#159154">Santander prodct recommendation</a>
									</div>
									<div class="discussion-teaser__item-details">
										<span>4 replies</span> · <span title="Wed Feb 01 2017 04:37:29 GMT+0100 (CET)">2 months ago</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

torneos/templates/torneos/index.html
{% extends "torneo.html" %}
{% load i18n staticfiles cms_tags menu_tags sekizai_tags %}

{% block title %}Torneos{% endblock title %}

    {% block feature %}
            <div class="feature-visual">
                <img src="{% static 'img/visuals/feature-default.jpg' %}" alt="">
            </div>
            <div class="feature-content">
                <section class="container cms-plugin cms-plugin-2210">
                    <div class="row      cms-plugin cms-plugin-2211">
                        <div class="col-md-24      cms-plugin cms-plugin-2212">
                            <div class="spacer      spacer-xs      cms-plugin cms-plugin-2213"></div>
                            <h1 class="cms-plugin cms-plugin-2214">Competiciones abiertas</h1>
                            <p class="hidden-xs cms-plugin cms-plugin-2214">¡¡¡Participa!!!</p>
                        </div>
                    </div>
                </section>
            </div>
    {% endblock feature %}


{% block content %}
<div class="container">
{% if latest_list %}
    {% for t in latest_list %}
    	<div class="row">
			<div class="col-md-3 icon-rounded">
                <div class="spacer spacer-xs"></div>
			    <img src="{{ MEDIA_URL }}{{ t.image.name }}" alt="" class="img-responsive"></img>
			</div>
			<div class="col-md-21">
			    <h4><a href="{% url 'torneos:torneos_detail_slug' t.t_id t.slug %}">{{ t.title }}</a></h4>
				<p>{{t.short_description}}
				<br /><sub>{{t.first_prize}} · 152 participantes · <span style="color: #ff0000;">Un mes para finalizar</span></sub></p>
			</div>
		</div>
    {% endfor %}
{% else %}
    <p>No polls are available.</p>
{% endif %}
<div class="spacer spacer-xl">&nbsp;</div>
</div>
{% endblock content %}

torneos/templates/torneos/submission_upload.html
{% extends "torneo.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
{% endblock breadcrumb %}

{% block content %}
<div class="container">

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

</div>
{% endblock %}