hokimicms/tools/server/src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^static/(?P<path>.*)$', 'django.contrib.staticfiles.views.serve', { 'insecure': True }),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT }),
) + i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('cms.urls')),
)

hokimicms/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

from django.contrib.auth import views as auth_views
from test.views import index, health

from machina.app import board

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += [url(r'^test$', index),
				url(r'^test/health$', health),]
				
urlpatterns += i18n_patterns(
#     url(r'^accounts/login/$', auth_views.login),
    url(r'^', include('torneos.urls', namespace="torneos", app_name="torneos"), name="torneos"),
    # url(r'^', include('competition.urls')),  # NOQA
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^', include('cms.urls')),
) + [url(r'^forum/', include(board.urls)),]

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

torneos/urls.py
from django.conf.urls import url

from .views import torneo_views
from .views.registration_views import RegistrationView
from .views.score_views import ScoreView
from .views import profile_view

app_name = "torneos"
urlpatterns = [
	url(r'^profile/$',  torneo_views.update_profile, name="profile"),
    url(r'^password/$', profile_view.change_password, name='change_password'),
	url(r'^signup/$', profile_view.signup, name='signup'),

    url(r'^account_activation_sent/$', profile_view.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        profile_view.activate, name='activate'),
	
	url(r'^competiciones/$', torneo_views.index, name='index'),
	url(r'^competiciones/(?P<torneo_id>[0-9]+)/$', torneo_views.detail, name='torneos_detail'),
	url(r'^competiciones/(?P<torneo_id>[0-9]+)/(?P<slug>[-\w]+)/$',  
		torneo_views.TorneoDetailView.as_view(), 
		name="torneos_detail_slug"),

    url(r'^competiciones/(?P<torneo_id>[0-9]+)/(?P<slug>[\w-]+)/register/$',
        RegistrationView.as_view(),
        name='register_for'),

    url(r'^competiciones/(?P<torneo_id>[0-9]+)/(?P<slug>[\w-]+)/submission/$',
        ScoreView.as_view(),
        name='submission_for'),
]

torneos/forms/profile_forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext, ugettext_lazy as _

from ..models.profile_model import  Profile

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        first_name = forms.CharField(required=True)
        last_name = forms.CharField(required=True)
        email = forms.EmailField(label='Your email', required=True)
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        bio = forms.CharField(widget=forms.Textarea)
        fields = ('bio',)

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

torneos/forms/score_forms.py
from django import forms
from django.contrib.auth.models import User
from ..models.score_model import Score
from ..models.torneo_model import Torneo


class ScoreForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=User.objects.all(),
            widget=forms.HiddenInput())
    competition = forms.ModelChoiceField(queryset=Torneo.objects.all(),
            widget=forms.HiddenInput())

    score = forms.CharField(widget = forms.HiddenInput(), required = False)
    error = forms.CharField(widget = forms.HiddenInput(), required = False)

    class Meta:
        model = Score
        fields = ('description', 'document')

torneos/views/mixins.py
from django import forms
from django.http import Http404
from django.contrib import messages
from django.views.generic import View
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from ..models.torneo_model import Torneo

import logging

logger = logging.getLogger(__name__)


class TorneoViewMixin(View):
    """A mixin class for adding a competition accessor to the class
    (i.e. self.get_competition()) and adding a competition object to
    the template context, if necessary."""
    def get_torneo(self):
        """Returns the competition for the given view.  This requires
        that self.kwargs be set"""
        if not hasattr(self, "_comp"):
            try:
                t_id = self.kwargs['torneo_id']
                self._comp = get_object_or_404(Torneo, t_id=t_id)
            except KeyError:
                msg = "Couldn't find comp_slug in kwargs"
                logger.error(msg)
                raise Http404(msg)

        return self._comp

    def dispatch(self, request, *args, **kwargs):
        """Overrides dispatch function to load competition
        information. Raises a Http404 if the competition with slug
        kwargs['comp_slug'] doesn't exist"""
        self.kwargs = kwargs
        self.get_torneo()  # Throws Http404 if not found
        parent = super(TorneoViewMixin, self)
        return parent.dispatch(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        """Overrides get_context_data to add 'competition' to the
        template context before rendering"""
        c = self.get_torneo()
        user = self.request.user

        try:
            team = c.team_set.get(members=user)
        except ObjectDoesNotExist:
            team = None

        context = {
            'torneo': c,
            'user_registered': c.is_user_registered(user),
            'user_team': team,
        }
        # Update the context with the parent's context
        parent = super(TorneoViewMixin, self)
        context.update(parent.get_context_data(*args, **kwargs))
        return context


class LoggedInMixin(View):
    """A mixin class for checking that a user is logged in"""
    redirect_field_name = "next"
    login_url = None

    def login_required(self, dispatch_function):
        """Wraps a function with login_required. Intended to be used
        to wrap a View's dispatch function"""
        return login_required(dispatch_function,
                              redirect_field_name=self.redirect_field_name,
                              login_url=self.login_url)

    def dispatch(self, request, *args, **kwargs):
        """Overrides dispatch by wrapping dispatch with
        login_required"""
        parent = super(LoggedInMixin, self)
        wrapped_function = self.login_required(parent.dispatch)
        return wrapped_function(request, *args, **kwargs)


class UserRegisteredMixin(TorneoViewMixin, LoggedInMixin):
    """A mixin class for checking that a user is registered for a
    competition"""

    def dispatch(self, request, *args, **kwargs):
        """Overrides dispatch and does the following
           - Checks that a user is authenticated
           - Loads the competition with slug kwargs['comp_slug']
               - Raises a Http404 otherwise
           - Checks that a user is reigstered for the loaded competition
               - Raises a Http404 if they aren't registered"""
        self.kwargs = kwargs    # Needed for get_competition()

        # Causes a 404 if comp_slug kwarg is bad or if the user
        # isn't registered for the corresponding competition
        self.registered_or_404(request)

        # Checks that a user is logged in before returning
        parent = super(UserRegisteredMixin, self)
        wrapped_function = self.login_required(parent.dispatch)
        return wrapped_function(request, *args, **kwargs)

    def registered_or_404(self, request):
        """Checks that the user is registered for the competition
        whose competition slug is kwargs['comp_slug']. If the user is
        not registered, raises Http404"""
        # Causes a 404 if the comp_slug kwarg is bad
        competition = self.get_torneo()
        if not competition.is_user_registered(request.user):
            raise Http404("User isn't registered")


# class ConfirmationMixin(FormView):
#     question = None
#     check_box_label = "OK"

#     def get_question(self):
#         if self.question is None:
#             raise Exception("question not set for ConfirmationMixin")
#         return self.question

#     def get_check_box_label(self):
#         return self.check_box_label

#     def get_context_data(self, **kwargs):
#         kwargs['question'] = self.get_question()
#         return super(FormView, self).get_context_data(**kwargs)

#     def get_form_class(self):

#         class ConfirmationForm(forms.Form):
#             confirmed = forms.BooleanField(required=False,
#                                            label=self.get_check_box_label())

#         return ConfirmationForm

#     def form_valid(self, form):
#         if form.cleaned_data['confirmed']:
#             return self.agreed()
#         return self.disagreed()

#     def agreed(self):
#         """If the user agreed, redirect them to the success url"""
#         return redirect(self.get_success_url())

#     def disagreed(self):
#         """If the user disagreed, redirect them to the success url"""
#         return redirect(self.get_success_url())


class CheckAllowedMixin(View):
    """This mixin throws a 404 if certain conditions are not met.

    At the beginning of the request, this mixin calls
    ``check_if_allowed()`` to see if the user is allowed to view the
    page. If not, it calls ``get_error_message()``, sets an error
    message with level ``self.message_level``, and calls
    ``was_not_allowed`` to determine how to handle the error. The
    default is to throw a 404.

    If the user is allowed to view the page, everything proceeds as
    usual.
    """
    error_message = "You cannot do that"
    message_level = messages.INFO

    def dispatch(self, request, *args, **kwargs):
        is_allowed = self.check_if_allowed(request)
        if not isinstance(is_allowed, bool):
            msg = "check_if_allowed method returned something "
            msg += "other than True or False"
            logger.warning(msg)
        if not is_allowed:
            msg = self.get_error_message(request)
            messages.add_message(request, self.message_level, msg)
            return self.was_not_allowed(request)

        parent = super(CheckAllowedMixin, self)
        return parent.dispatch(request, *args, **kwargs)

    def check_if_allowed(self, request):
        """Called to see if a user is allowed to view this page. It
        should return True if they're allowed, and False otherwise.
        """
        raise Exception("check_if_allowed() is not overridden.")

    def get_error_message(self, request):
        """Called to get the user's error message. If not overridden,
        we'll just use ``self.error_message``
        """
        return self.error_message

    def was_not_allowed(self, request):
        """Called if check_if_allowed returned False. If not
        overridden, we'll just throw a 404"""
        raise Http404(self.get_error_message(request))


# class RequireRunningMixin(CheckAllowedMixin):
#     """This mixin throws a 404 if the current competition is not running
#     """
#     error_message = "You cannot do that because the competition is not running"

#     def check_if_allowed(self, request):
#         """Called to see if a user is allowed to view this page.
#         """
#         # If the competition is running, they're allowed to view it
#         return self.get_competition().is_running

#     def get_competition(self):
#         """Gets the instance of the competition to check.  

#         You could just inherit from CompetitionViewMixin, which
#         provides get_competition, just make sure that it's listed
#         before RequireRunningMixin when inheriting in the view
#         """
#         raise Exception("get_competition() not implemented")


# class RequireNotRunningMixin(CheckAllowedMixin):
#     """This mixin throws a 404 if the current competition is running
#     """
#     error_message = "You cannot do that because the competition is running"

#     def check_if_allowed(self, request):
#         """Called to see if a user is allowed to view this page.
#         """
#         # If the competition is running, they're NOT allowed to view it
#         return not self.get_competition().is_running

#     def get_competition(self):
#         """Gets the instance of the competition to check.  

#         You could just inherit from CompetitionViewMixin, which
#         provides get_competition, just make sure that it's listed
#         before RequireRunningMixin when inheriting in the view
#         """
#         raise Exception("get_competition() not implemented")


class RequireOpenMixin(CheckAllowedMixin):
    """This mixin throws a 404 if the current competition is not open
    """
    error_message = "You cannot do that because the competition is not open"

    def check_if_allowed(self, request):
        """Called to see if a user is allowed to view this page.
        """
        # If the competition is open, they're allowed to view it
        # return self.get_torneo().is_open
        return True

    def get_torneo(self):
        """Gets the instance of the competition to check.  

        You could just inherit from CompetitionViewMixin, which
        provides get_competition, just make sure that it's listed
        before RequireRunningMixin when inheriting in the view
        """
        raise Exception("get_competition() not implemented")

torneos/views/profile_view.py
from django.shortcuts import render, redirect

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string

from django.contrib import messages
from django.contrib.auth import login, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode

from ..tokens import account_activation_token
from ..forms.profile_forms import SignUpForm



# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate your Hokimi account'
            message = render_to_string('profiles/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            return redirect('torneos:account_activation_sent')
    else:
        form = SignUpForm()
    return render(request, 'profiles/signup.html', {'form': form})    

def account_activation_sent(request):
    return render(request, 'profiles/account_activation_sent.html')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('pages-root')
    else:
        return render(request, 'account_activation_invalid.html')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('torneos:change_password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'profiles/change_password.html', {
        'form': form
    })

hokimicms/templates/base.html
{% extends "base_root.html" %}
{% load i18n staticfiles cms_tags menu_tags sekizai_tags %}

{% block body_class %}tpl-base{% endblock %}

{% block extend_root %}
{% block header %}
{# INFO: navbar concept: http://getbootstrap.com/components/#navbar #}
<header class="navbar navbar-head js-navbar-head navbar-inverse navbar-fixed-top">
    <div class="container">
        {# INFO: the logo should be placed first for seo reasons #}
        <div class="navbar-header">
            {# INFO: the logo should be placed first for seo reasons #}
            <h1 class="navbar-brand">
                <a href="/">
                    <span class="sr-only">{ request.site.name }}</span>
                    <img src="{% static "img/logo-main@print.png" %}" alt="{{ request.site.name }}" />
                </a>
            </h1>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".js-navbar-header">
                {% for row in 123|make_list %}<span class="icon-bar"></span>{% endfor %}
            </button>
        </div>

        {# INFO: ensure the anchor names are callable #}
        <h2 class="sr-only">{% trans "Shortcuts" %}</h2>
        <ul class="skip-links">
            <li><a href="/" title="[Alt + 0]" accesskey="0">{% trans "Go to home" %}</a></li>
            <li><a href="#navigation" title="[Alt + 1]" accesskey="1">{% trans "Jump to navigation" %}</a></li>
            <li><a href="#content" title="[Alt + 2]" accesskey="2">{% trans "Jump to content" %}</a></li>
            <li><a href="#footer" title="[Alt + 3]" accesskey="3">{% trans "Contact" %}</a></li>
        </ul>

        <div class="navbar-collapse collapse js-navbar-header">
            {% block navbar %}
            <nav class="nav navbar-main navbar-right" id="navigation">
                <h2 class="sr-only">{% trans "Navigation" %}</h2>
                {% render_model_block request.current_page "changelist" %}
                {% with dropdown="true" %}
                <ul class="nav navbar-nav">
                    {% show_menu 0 0 0 0 "includes/menu/navigation.html" %}
                    <li class="divider" role="presentation"><span class="sr-only">{% trans "Separator" %}</span></li>
                    {% show_menu_below_id "meta" 0 0 0 0 "includes/menu/navigation.html" %}
                    {% if user.is_authenticated %}
                    <li class="child">
                      <a class="dropdown-toggle" data-toggle="dropdown">

<div class="Main-nav__account-button__avatar" style="background-image: url({% static "img/default-avatar.png" %});"></div>

</a>
                      <ul class="dropdown-menu">
                        <li class="dropdown-header">Hi, {{user.get_username}}</li>
                        <li class="divider"></li>
                        <li><a href="#" style="text-align:left">Tu perfil</a></li>
                        <li><a href="{% url 'torneos:profile' %}" style="text-align:left">Configuración</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'logout' %}?next=/" style="text-align:left">Salir</a></li>
                      </ul>
                    </li> 
                    {% endif %}                   
                </ul>
                {% endwith %}
                {% endrender_model_block %}
            </nav>
            {% endblock navbar %}
        </div>
    </div>
</header>
{% endblock header %}

<!-- start: content -->
<hr class="sr-only" />
<div class="feature-wrapper js-feature-wrapper">
    {% block feature %}
        {% placeholder "feature" or %}
            <div class="feature-visual">
                <img src="{% static 'img/visuals/feature-default.jpg' %}" alt="">
            </div>
            <div class="feature-content text-center">
                <div class="spacer spacer-xs">&nbsp;</div>
                <h1>{% page_attribute "page_title" %}</h1>
            </div>
        {% endplaceholder %}
    {% endblock feature %}
</div>

{% block breadcrumb %}
{% if not request.current_page.is_home %}
<!-- start: breadcrumb -->
{# INFO: breadcrumb concept: http://getbootstrap.com/components/#breadcrumbs #}
<nav class="navbar navbar-breadcrumb" role="navigation">
    <h3 class="sr-only">{% trans "You are here" %}</h3>
    <div class="container">
        <ol class="breadcrumb">
            {% block extend_breadcrumb %}
            {% show_breadcrumb 0 "includes/menu/breadcrumb.html" %}
            {% endblock extend_breadcrumb %}
        </ol>
    </div>
</nav>
<!-- end: breadcrumb -->
{% endif %}
{% endblock breadcrumb %}

{% block messages %}
{% if messages %}
<!-- start: messages -->
<div class="container">
    {% include "includes/messages.html" %}
</div>
<!-- end: messages -->
{% endif %}
{% endblock messages %}

{% block extend_base %}
    {% block content %}{% endblock %}
{% endblock extend_base %}

<div class="container">
    {% static_placeholder "contact-theme" %}
</div>

<hr class="sr-only" />
<!-- end: content -->

{% block footer %}
<!-- start: footer -->
<footer class="footer">
    <h2 class="sr-only" id="footer">{% trans "Sitemap" %}</h2>

    <div class="footer-copyright">
        <div class="container">
            {% render_model_block request.current_page "changelist" %}
            <ul class="list-inline">
                <li class="pull-right"><a href="#page-top" data-spy="scroll">{% trans "Back to top" %} <span class="fa fa-right fa-arrow-up"></span></a></li>
                {% show_menu_below_id "footer" 0 0 100 100 "includes/menu/navigation.html" %}
                {% language_chooser "includes/menu/langnav.html" "native" %}
            </ul>
            {% endrender_model_block %}
            {% static_placeholder "footer" %}
        </div>
    </div>

    <div class="footer-theme">
        <div class="container">
            {% static_placeholder "footer-theme" %}
        </div>
    </div>
</footer>
<!-- end: footer -->
{% endblock footer %}

{% addtoblock "js" %}<script src="{% static 'js/addons/cl.explorer.js' %}"></script>{% endaddtoblock %}
{% endblock extend_root %}

hokimicms/templates/base_old.html
{% load staticfiles i18n cms_tags sekizai_tags menu_tags %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% page_attribute 'meta_description' %}">
    <meta name="author" content="">

    <title>
        {% block title %}
            {% page_attribute "page_title" %} - {{ request.site.name }}
        {% endblock title %}
    </title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- django CMS -->
    {% render_block "css" %}

    <!-- Divio Cloud -->
    {{ ALDRYN_SNAKE.render_head }}

    <!-- django CMS toolbar adjustment -->
    {% if request.toolbar %}
    <style>
        .cms-toolbar-expanded .navbar-custom {
            margin-top: 45px;
        }
    </style>
    {% endif %}

</head>

<body>
    <!-- django CMS Toolbar -->
    {% cms_toolbar %}

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="/">{{ request.site.name }}</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse"id="bs-example-navbar-collapse-1"> 
                <ul class="nav navbar-nav navbar-right">
                    {% show_menu 0 0 100 100 %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header  -->
    {% placeholder header or %}    
        <!-- Set your background image for this header on the line below. -->
        <header class="intro-header" style="background-image: url({% static 'img/about-bg.jpg' %})">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                        <div class="page-heading">
                            <h1>{% page_attribute "page_title" %}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    {% endplaceholder %}

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {% static_placeholder "footer" %}
                    <p class="copyright text-muted">Copyright &copy; {{ request.site.name }} {% now "Y" %}</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

    <!-- django CMS -->
    {% render_block "js" %}

    <!-- Divio Cloud -->
    {{ ALDRYN_SNAKE.render_tail }}
</body>

</html>

hokimicms/templates/content.html
{% extends "base.html" %}
{% load cms_tags %}

{% block content %}
    {% placeholder "content" %}
{% endblock content %}

hokimicms/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
<div class="container">
	{% placeholder "content" %}
</div>
{% endblock content %}

hokimicms/templates/sidebar_left.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
    <div class="content">
        {% placeholder "content" %}
    </div>
{% endblock content %}

hokimicms/templates/sidebar_right.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block content %}
    <div class="content">
        {% placeholder "content" %}
    </div>
    <div class="sidebar">
        {% placeholder "sidebar" %}
    </div>
{% endblock content %}

hokimicms/templates/torneo.html
{% extends "base.html" %}
{% load cms_tags staticfiles sekizai_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block css %}
	{% addtoblock "css" %}
		<link href="{% static 'css/hokimi.css' %}" rel="stylesheet" type="text/css" />
	{% endaddtoblock %}
{% endblock %}

{% block breadcrumb %}
{% endblock breadcrumb %}


{% block feature %}
<div class="spacer
     spacer-md
    "></div>
{% endblock feature %}

{% block content %}
<div class="container">
	{% placeholder "content" %}
</div>
{% endblock content %}

hokimicms/templates/tpl_home.html
{% extends "fullwidth.html" %}

{% block body_class %}tpl-home{% endblock %}